name: pyspatialstats
channels:
  - defaults
  - conda-forge
dependencies:
  - cython
  - numpy>=2.2.1
  - pytest
  - scipy
  - joblib
  - pydantic
  - pandas
  - statsmodels
  - xarray
  - scikit-learn
