name: test

on: workflow_call

jobs:
  test:
    name: Run the package tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup micromamba and install dependencies
        uses: mamba-org/setup-micromamba@v2
        with:
          init-shell: bash
          environment-name: pyspatialstats-tests-env
          environment-file: environment.yml

      - name: Locally install pyspatialstats
        shell: bash -l {0}
        run: |
          micromamba activate pyspatialstats-tests-env
          python -m pip install -e .

      - name: Debug NumPy installation
        shell: bash -l {0}
        run: |
          micromamba activate pyspatialstats-tests-env
          python -c "
          import numpy as np
          import os
          import glob
          numpy_path = os.path.dirname(np.__file__)
          print('NumPy location:', numpy_path)
          print('NumPy version:', np.__version__)
          random_lib = os.path.join(numpy_path, 'random', 'lib')
          core_lib = os.path.join(numpy_path, '_core', 'lib')
          print('Random lib exists:', os.path.exists(random_lib))
          print('Random lib contents:', glob.glob(os.path.join(random_lib, '*')))
          print('Core lib exists:', os.path.exists(core_lib))
          print('Core lib contents:', glob.glob(os.path.join(core_lib, '*')))
          
          print('test 1')
          from pyspatialstats.random.random import Random
          print(Random().np_randpoisson(1, 10))
          
          print('test 2')
          import pyspatialstats
          
          import numpy as np
          
          from pyspatialstats.bootstrap.mean import py_bootstrap_mean
          from tests.bootstrap.np_stats import np_bootstrap_mean
          
          n_bootstraps = 1000
          data = np.random.randn(10).astype(np.float64)

          result = py_bootstrap_mean(data, n_bootstraps, seed=42)

          assert isinstance(result.mean, float)
          assert isinstance(result.se, float)

          assert -10 < result.mean < 10
          assert 0 < result.se < 10
          
          
          "

      - name: Run tests
        shell: bash -l {0}
        run: |
          micromamba activate pyspatialstats-tests-env
          python -c "import numpy, sys; print(numpy.__version__, numpy.__file__)"
          python -m pytest tests