name: test

on: workflow_call

jobs:
  test:
    name: Run the package tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup micromamba and install dependencies
        uses: mamba-org/setup-micromamba@v2
        with:
          init-shell: bash
          environment-name: pyspatialstats-tests-env
          environment-file: environment.yml

      - name: Locally install pyspatialstats
        shell: bash -l {0}
        run: |
          micromamba activate pyspatialstats-tests-env
          python -m pip install -e .

      - name: Debug NumPy installation
        shell: bash -l {0}
        run: |
          micromamba activate pyspatialstats-tests-env
          python -c "
          import numpy as np
          import os
          import glob
          numpy_path = os.path.dirname(np.__file__)
          print('NumPy location:', numpy_path)
          print('NumPy version:', np.__version__)
          random_lib = os.path.join(numpy_path, 'random', 'lib')
          core_lib = os.path.join(numpy_path, '_core', 'lib')
          print('Random lib exists:', os.path.exists(random_lib))
          print('Random lib contents:', glob.glob(os.path.join(random_lib, '*')))
          print('Core lib exists:', os.path.exists(core_lib))
          print('Core lib contents:', glob.glob(os.path.join(core_lib, '*')))
          
          from pyspatialstats.random.random import Random
          print(Random().np_randpoisson(1, 10))
          
          import pyspatialstats
          print(pyspatialstats.__version__)
          "

      - name: Run tests
        shell: bash -l {0}
        run: |
          micromamba activate pyspatialstats-tests-env
          python -c "import numpy; print(numpy.__version__)"
          python -m pytest tests/grouped_stats
          